POST http://localhost:4400/employee/register
Content-Type: application/json

{
    "name": "Daniel Kitheka",
    "email": "dan@yopmail.com",
    "phone_no": "0754876562",
    "id_no": 363784563,
    "KRA_PIN": "ADjCC22XXY3",
    "NHIF_NO": "1170784J43",
    "NSSF_NO": "ksdhu7879DS",
    "password": "12345678"
}


### login 
POST http://localhost:4400/employee/login
Content-Type: application/json

{
    "email": "dan@yopmail.com",
    "password": "12345678"
}

### fetching employees
GET http://localhost:4400/employee
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZV9pZCI6ImRmZTI4ZDA3LTJhM2EtNDdmNC05MDBjLWNmMzc2ZTE5OThkYiIsIm5hbWUiOiJEYW5pZWwgS2l0aGVrYSIsImVtYWlsIjoiZGFuQHlvcG1haWwuY29tIiwicm9sZSI6ImVtcGxveWVlIiwiaWF0IjoxNjk5NTIyOTkxLCJleHAiOjE2OTk1MjY1OTF9.oY55cnxQ6nVeQIfvtY2J8nVo2gXjGbI4JSK8x-q1fQ4


### fetching one employee
GET http://localhost:4400/employee/0adbb3b5-dead-448f-9ca1-44f93d0e5527
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZV9pZCI6ImRmZTI4ZDA3LTJhM2EtNDdmNC05MDBjLWNmMzc2ZTE5OThkYiIsIm5hbWUiOiJEYW5pZWwgS2l0aGVrYSIsImVtYWlsIjoiZGFuQHlvcG1haWwuY29tIiwicm9sZSI6ImVtcGxveWVlIiwiaWF0IjoxNjk5NTIzMzk0LCJleHAiOjE2OTk1MjY5OTR9.QxZyCOD7_VF6vGef36vbr5JAFAKB6-RvolRw9TLeOy4

### checking user details
GET http://localhost:4400/employee/check_user_details
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZV9pZCI6ImRmZTI4ZDA3LTJhM2EtNDdmNC05MDBjLWNmMzc2ZTE5OThkYiIsIm5hbWUiOiJEYW5pZWwgS2l0aGVrYSIsImVtYWlsIjoiZGFuQHlvcG1haWwuY29tIiwicm9sZSI6ImVtcGxveWVlIiwiaWF0IjoxNjk5NDM3NTY1LCJleHAiOjE2OTk0NDExNjV9.2-FK-BOh1TLzkHHTxX3eF3XLMV79ta1-LUNtoIaFB8E
