POST http://localhost:4400/employee/register
Content-Type: application/json

{
    "name": "DaNIel Kitheka",
    "email": "dan04@yopmail.com",
    "phone_no": "7509294560",
    "id_no": 310444531,
    "KRA_PIN": "KRAF43792Y",
    "NHIF_NO": "NHIF93040H",
    "NSSF_NO": "NS118N34D",
    "password": "12345678"
}


### login 
POST http://localhost:4400/employee/login
Content-Type: application/json

{
    "email": "dan04@yopmail.com",
    "password": "12345678"
}

### fetching employees
GET http://localhost:4400/employee
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZV9pZCI6IjhkNzYyZjkzLTQ4MDUtNDg1ZS1hNTczLTQ2NDdjY2E3YTAzYSIsIm5hbWUiOiJEYU5JZWwgS2l0aGVrYSIsImVtYWlsIjoiZGFuMDRAeW9wbWFpbC5jb20iLCJyb2xlIjoiZW1wbG95ZWUiLCJpc0RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MDI5NzcxNzYsImV4cCI6MTcwMzA2MzU3Nn0.kjNMnzaDp2ZSc9EvDJFeApfFewqwEknyoCFwhSKWBRM


### fetching one employee
GET http://localhost:4400/employee/4098b7ca-4cd3-42f0-9504-78d94f59f162
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZV9pZCI6ImRmZTI4ZDA3LTJhM2EtNDdmNC05MDBjLWNmMzc2ZTE5OThkYiIsIm5hbWUiOiJEYW5pZWwgS2l0aGVrYSIsImVtYWlsIjoiZGFuQHlvcG1haWwuY29tIiwicm9sZSI6ImVtcGxveWVlIiwiaXNEZWxldGVkIjpmYWxzZSwiaWF0IjoxNzAwMzQyNjEyLCJleHAiOjE3MDAzNDYyMTJ9.YVvDdAanyf3HpS4Cgq8VJKLVxVU51zc0JBW0xYENXQ8

### checking user details
GET http://localhost:4400/employee/check_user_details
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZV9pZCI6ImRmZTI4ZDA3LTJhM2EtNDdmNC05MDBjLWNmMzc2ZTE5OThkYiIsIm5hbWUiOiJEYW5pZWwgS2l0aGVrYSIsImVtYWlsIjoiZGFuQHlvcG1haWwuY29tIiwicm9sZSI6ImVtcGxveWVlIiwiaXNEZWxldGVkIjp0cnVlLCJpYXQiOjE3MDA0NjQwOTIsImV4cCI6MTcwMDU1MDQ5Mn0.q3gT-P3dN8R3pilhSYbJD576jMg1KxN6xKgNNNVMCps

### Delete Employee
PUT http://localhost:4400/employee/4098b7ca-4cd3-42f0-9504-78d94f59f162
Content-Type: application/json

{
    "isDeleted": true
}



####PROJECT ROUTES
POST http://localhost:4400/projects/create
Content-Type: application/json

{
    "project_name": "Project 1234",
    "project_description": "Build a construction 1234",
    "project_deadline": "2023-04-05",
    "assigned_to": ""
}

###FETCH ALL PROJECTS

GET http://localhost:4400/projects/


### Fetch one project
GET http://localhost:4400/projects/e7173ed3-545d-43d4-a463-6cf79c175fe5

### Deleting a project 
DELETE http://localhost:4400/projects/19ed8e8f-7cb3-44ef-9790-c7078949a38c



### Update a project by ID
PUT http://localhost:4400/projects/ffc3025c-42d1-4422-896a-964af22107fd
Content-Type: application/json

{
    "project_name": "Project AB",
    "project_description": "Build a construction AB",
    "project_deadline": "2024-05-05",
    "assigned_to": ""
}


###TEAMS TOUTES

POST http://localhost:4400/teams/create
Content-Type: application/json

{
    "team_Name": "Manchester Red",
    "members": "dd74433f-c1f4-4305-9e8d-6cca13384712 , 915d2e63-db51-47ea-a027-74f14955178e",
    "project_assigned": "7992cb0d-4006-46d3-83da-7c9b035af96f"
}

### GET ALL TEAMS

GET http://localhost:4400/teams/


### GET ONE TEAM
GET http://localhost:4400/teams/41177255-ccd1-4020-b301-8209ff3650a3
